spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/DEV
#    #url: jdbc:mysql://mysql-container:3306/dev
#    username: root
#    password: Thtn9669@
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:h2:mem:dev
    driverClassName: org.h2.Driver
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: false
springdoc:
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /api